all:
	g++ main.cpp llist.cpp llist.h arraystack.cpp arraystack.h -o main.o

stack:
	g++ main.cpp arraystack.cpp arraystack.h -o main.o

linkedlist:
	g++ main.cpp llist.cpp llist.h -o llist.o

clean:
	rm *.o
